const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db,view='home',editing=null,files=[];
const initial={notes:[],tasks:[],books:['General'],scratch:''};
const request=indexedDB.open('mi-cuaderno',1);request.onupgradeneeded=()=>request.result.createObjectStore('data');request.onerror=()=>toast('No se puede abrir el almacenamiento. Prueba fuera del modo privado.');request.onsuccess=()=>{db=request.result;const r=db.transaction('data').objectStore('data').get('state');r.onsuccess=()=>{state=r.result||structuredClone(initial);render();};};
let state=structuredClone(initial);
function save(){return new Promise((resolve,reject)=>{if(!db)return reject(Error('Almacenamiento no disponible'));const t=db.transaction('data','readwrite');t.objectStore('data').put(state,'state');t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',3500);}
async function persist(){try{await save();return true;}catch(e){toast('No se pudo guardar. Exporta una copia y comprueba el espacio disponible.');return false;}}
const id=()=>crypto.randomUUID();
$('#date').textContent=new Intl.DateTimeFormat('es',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());
function noteCards(notes){return notes.length?notes.map(n=>`<button class="card" data-note="${esc(n.id)}"><strong>${esc(n.title||'Sin título')}</strong><p>${esc(n.body.slice(0,130))}</p><span class="meta">${esc(n.book)} · ${new Date(n.updated).toLocaleDateString('es')}${n.files.length?' · '+n.files.length+' adjunto(s)':''}</span></button>`).join(''):'<div class="empty">Tus ideas tienen un lugar aquí.<br>Crea tu primera nota.</div>';}
function taskCards(tasks){return tasks.length?tasks.map(t=>`<div class="task ${t.done?'done':''}"><input type="checkbox" data-task="${esc(t.id)}" id="t-${esc(t.id)}" ${t.done?'checked':''}><label for="t-${esc(t.id)}">${esc(t.text)}</label><button aria-label="Eliminar tarea" data-remove-task="${esc(t.id)}">×</button></div>`).join(''):'<div class="empty">No hay tareas pendientes.</div>';}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const query=$('#search').value.toLocaleLowerCase();const notes=state.notes.filter(n=>`${n.title} ${n.body} ${n.book}`.toLocaleLowerCase().includes(query)).sort((a,b)=>b.updated-a.updated);const tasks=state.tasks.filter(t=>t.text.toLocaleLowerCase().includes(query));let html='';if(query){html='<div class="section-head"><h2>Resultados</h2></div>'+noteCards(notes)+'<div class="section-head"><h2>Tareas</h2></div>'+taskCards(tasks);}else if(view==='home'){html=`<div class="actions"><button class="action green" data-action="new"><strong>＋ Nota nueva</strong><span>▤</span></button><button class="action purple" data-action="task"><strong>＋ Tarea nueva</strong><span>☑</span></button></div><div class="shortcuts"><button data-action="task"><span>☑</span>Tareas</button><button data-action="book"><span>▣</span>Libreta</button><button data-action="audio"><span>♩</span>Grabadora</button><button data-action="camera"><span>▧</span>Cámara</button></div><div class="section-head"><h2>Bloc de notas</h2><button data-action="convert">Crear nota</button></div><textarea class="scratch" id="scratch" placeholder="Empieza a escribir…" aria-label="Bloc de notas">${esc(state.scratch)}</textarea><p class="caption" id="scratch-status">Guardado en este dispositivo</p><div class="section-head"><h2>Notas recientes</h2><button data-view="notes">Ver todas</button></div>${noteCards(notes.slice(0,3))}`;}else if(view==='notes'){html='<div class="section-head"><h2>Notas</h2><button data-action="new">＋ Nueva</button></div>'+noteCards(notes);}else if(view==='tasks'){html='<div class="section-head"><h2>Tareas</h2><button data-action="task">＋ Nueva</button></div>'+taskCards(tasks);}else if(view==='books'){html='<div class="section-head"><h2>Libretas</h2><button data-action="book">＋ Nueva</button></div>'+state.books.map(b=>`<button class="card" data-book="${esc(b)}"><strong>▣ ${esc(b)}</strong><span class="meta">${state.notes.filter(n=>n.book===b).length} notas</span></button>`).join('');}else{html='<div class="section-head"><h2>Tu cuaderno</h2></div><div class="settings"><button data-view="tasks">☑ Mis tareas</button><button data-action="export">Exportar copia de seguridad</button><button data-action="import">Importar copia de seguridad</button><p>Las notas y los adjuntos se guardan en este dispositivo. Exporta copias periódicas: borrar los datos del navegador elimina este cuaderno.</p><p>Para instalar: abre la URL en Safari, pulsa Compartir y Añadir a pantalla de inicio.</p></div>';}$('#content').innerHTML=html;}
function openNote(note=null){editing=note?.id||null;files=structuredClone(note?.files||[]);$('#title').value=note?.title||'';$('#body').value=note?.body||'';$('#book').innerHTML=state.books.map(b=>`<option>${esc(b)}</option>`).join('');$('#book').value=note?.book||state.books[0];$('#delete').hidden=!note;$('#editor-label').textContent=note?'Editar nota':'Nueva nota';$('#attachment').value='';$('#attachment').removeAttribute('capture');$('#attachment').accept='image/*,application/pdf,audio/*';showFiles();$('#editor').showModal();}
function showFiles(){$('#attachments').innerHTML=files.map((f,i)=>`${f.type.startsWith('image/')?`<img src="${esc(f.data)}" alt="${esc(f.name)}">`:''}<a href="${esc(f.data)}" download="${esc(f.name)}">${esc(f.name)}</a><button type="button" data-remove-file="${i}" class="danger">Quitar adjunto</button>`).join('');}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;$('#search').value='';render();window.scrollTo(0,0);}if(b.dataset.note)openNote(state.notes.find(n=>n.id===b.dataset.note));if(b.dataset.book){$('#search').value=b.dataset.book;render();}if(b.dataset.removeTask){state.tasks=state.tasks.filter(t=>t.id!==b.dataset.removeTask);await persist();render();}if(b.dataset.removeFile!==undefined){files.splice(Number(b.dataset.removeFile),1);showFiles();}const action=b.dataset.action;if(action==='new')openNote();if(action==='task'){const text=prompt('¿Qué tienes que hacer?');if(text?.trim()){state.tasks.push({id:id(),text:text.trim(),done:false});await persist();view='tasks';render();}}if(action==='book'){const name=prompt('Nombre de la libreta');if(name?.trim()&&!state.books.includes(name.trim())){state.books.push(name.trim());await persist();view='books';render();}}if(action==='convert'){if(!state.scratch.trim())return toast('Escribe primero en el bloc.');openNote();$('#body').value=state.scratch;}if(action==='camera'||action==='audio'){openNote();$('#attachment').accept=action==='camera'?'image/*':'audio/*';if(action==='camera')$('#attachment').setAttribute('capture','environment');if(action==='audio')toast('Adjunta una grabación desde Archivos.');$('#attachment').click();}if(action==='export'){await persist();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:1,state})],{type:'application/json'}));a.download='mi-cuaderno-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000);}if(action==='import')$('#import').click();});
$('#search').addEventListener('input',render);
let scratchTimer;document.addEventListener('input',e=>{if(e.target.id==='scratch'){state.scratch=e.target.value;$('#scratch-status').textContent='Guardando…';clearTimeout(scratchTimer);scratchTimer=setTimeout(async()=>{if(await persist())if($('#scratch-status'))$('#scratch-status').textContent='Guardado en este dispositivo';},350);}});
document.addEventListener('change',async e=>{if(e.target.dataset.task){state.tasks.find(t=>t.id===e.target.dataset.task).done=e.target.checked;await persist();render();}});
$('#cancel').onclick=()=>$('#editor').close();
$('#note-form').onsubmit=async e=>{e.preventDefault();const n={id:editing||id(),title:$('#title').value.trim(),body:$('#body').value,book:$('#book').value,updated:Date.now(),files};if(!n.title&&!n.body.trim()&&!files.length)return toast('Escribe o adjunta algo antes de guardar.');const before=structuredClone(state.notes);const pos=state.notes.findIndex(x=>x.id===n.id);if(pos>=0)state.notes[pos]=n;else state.notes.push(n);if(await persist()){$('#editor').close();render();toast('Nota guardada');}else state.notes=before;};
$('#delete').onclick=async()=>{if(confirm('¿Eliminar esta nota?')){state.notes=state.notes.filter(n=>n.id!==editing);if(await persist()){$('#editor').close();render();}}};
$('#attachment').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>12*1024*1024)return toast('El adjunto debe ocupar menos de 12 MB.');const reader=new FileReader();reader.onload=()=>{files.push({name:f.name,type:f.type||'application/octet-stream',data:reader.result});showFiles();};reader.onerror=()=>toast('No se pudo leer el archivo.');reader.readAsDataURL(f);};
function validState(s){return s&&Array.isArray(s.books)&&s.books.length>0&&s.books.every(b=>typeof b==='string')&&typeof s.scratch==='string'&&Array.isArray(s.tasks)&&s.tasks.every(t=>typeof t.id==='string'&&typeof t.text==='string'&&typeof t.done==='boolean')&&Array.isArray(s.notes)&&s.notes.every(n=>typeof n.id==='string'&&typeof n.title==='string'&&typeof n.body==='string'&&s.books.includes(n.book)&&Number.isFinite(n.updated)&&Array.isArray(n.files)&&n.files.every(f=>typeof f.name==='string'&&typeof f.type==='string'&&typeof f.data==='string'&&/^data:[^,]*;base64,/.test(f.data)&&!/^data:(text\/html|image\/svg\+xml)/i.test(f.data)));}
$('#import').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(data.version!==1||!validState(data.state))throw Error();if(!confirm('Esta copia sustituirá las notas actuales. ¿Continuar?'))return;const previous=state;state=data.state;if(await persist()){render();toast('Copia restaurada');}else state=previous;}catch{toast('La copia no es válida.');}finally{e.target.value='';}};
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
